fail_fast: false
repos:
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.1.1
    hooks:
      - id: clang-format
        args: [--style=file, -i]
  - repo: local
    hooks:
      - id: code-scanner
        name: code-scanner
        entry: ./code-scanner.bat
        language: script
        files: ^$
        always_run: true
